### ISSUE TITLE
Find replacement for Travis

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/NightShift#10]
Github Actions?
Circle CI?

**Comment by mwbenowitz** [comment]
I'd use Github Actions! It depends a bit on where you'd like to deploy the code but in general it is very reliable, transparent and has solutions for most common use cases.

**Comment by klinga** [comment]
@mwbenowitz 👍 
It's probably embarrassing, but I was oblivious to changes in Travis. I still have some credits to go so this is not pressing, but I will try to make the transition soon. Another thing to learn...

**Comment by klinga** [comment]
RP https://github.com/BookOps-CAT/NightShift/pull/18

**Comment by klinga** [comment]
https://github.com/BookOps-CAT/NightShift/commit/a690607b49029b0ab1a0989ee0b5d7e7c7e68703
